### ISSUE TITLE
Select don't focus input on arrow click

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-select#1]
## Actual result

![react-select](https://user-images.githubusercontent.com/24652543/36149919-b56fe30c-10d2-11e8-814d-bf54eed03d1c.gif)

## Expected result

![react-select-2](https://user-images.githubusercontent.com/24652543/36149951-d3dbe16a-10d2-11e8-8eea-f43d449396e7.gif)

**Comment by asergeev-sc** [comment]
In 2.0.15 release bug is not reproducible any more
