### ISSUE TITLE
MultiSelect Functionality is lost

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/react-select#11]
2.0.9 does not support multiselect. After rollback to 1.0.0-rc.5-oc.6 multiselect works.

**Comment by asergeev-sc** [comment]
@nczeranka 
In v1.x multi-select mode enabled via setting **multi** property to **true** value (https://github.com/JedWatson/react-select/tree/v1.x#select-props)
In v2.x property is renamed to **isMulti** (see https://github.com/JedWatson/react-select#props)

If you open https://opuscapita.github.io/react-select/branches/master/?currentComponentName=Select&showSidebar=true and add ```isMulti={true}``` into any  ```<Select>...</Select>```, you'll see that it works.

**Comment by nczeranka** [comment]
Was not aware of the incompatible changes of the props between react-select 1.x and 2.
Thanks.
