### ISSUE TITLE
Disabled state is visually equal to enabled state

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-select#12]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 2h
Remaining Estimation | 2h

https://github.com/OpusCapita/minsk-core-externals/issues/435

**Comment by estambakio-sc** [comment]
Demo: https://opuscapita.github.io/react-select/branches/issue-12/?currentComponentName=Select&showSidebar=true

QA: please check if `disabled` inputs are `grey` (all 4 components).

**Comment by nstoliar-sc** [comment]
Tested. Field in view mode differs from editable fields. Please, merge with master branch.
