### ISSUE TITLE
Update react-select dependency version

### ISSUE THREAD

**Issue by dsanko-sc** [OpusCapita/react-select#16]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 1h
Remaining Estimation | 1h

Update react-select dependency version to 2.4.4

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/486

**Comment by dsanko-sc** [comment]
Completed.
For QA: test it together with https://github.com/OpusCapita/grails-boilerplate/issues/120, https://github.com/OpusCapita/grails-text-table/issues/64
War file: com/jcatalog/test/jcdemo/8.12.GA-boiler-issue-120-SNAPSHOT/jcdemo-8.12.GA-boiler-issue-120-20191209.093200-1.war
Link: https://demo.core.dev.opuscapita.com/minsk-core-demo/boiler-issue-120

**Comment by nstoliar-sc** [comment]
Tested. React-select inputs dropdown for Boilerplate and text-table editors are displayed correctly. Scrolling for react-select inputs dropdown works correctly. Please, merge with master branch.
