### ISSUE TITLE
React-selects are not closed if it was opened by arrow

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/react-select#4]
Meta-Info | Value
-- | --
ExtProjectId |  JCPIM-01.3
Original Estimation | ???h
Remaining Estimation | ???h

React-selects are not closed if it was opened by arrow and then user clicks on other place of page.

![266](https://user-images.githubusercontent.com/25082017/43832361-de734574-9b0f-11e8-82cd-6342507a58c2.png)

**Comment by asergeev-sc** [comment]
But is not reproducible in 2.0.15 version
